## Install the Transformers, Datasets, and Evaluate libraries to run this notebook.


logging.set_verbosity_error() is used beacuse it tells what model it have used by default i have removed it u can use it or give our own model so that no error was raised

In [ ]:
!pip install datasets evaluate transformers[sentencepiece]

In [ ]:
from huggingface_hub import notebook_login
notebook_login()

In [ ]:
from transformers import pipeline,logging


In [ ]:
generator = pipeline("text-generation")
ans=generator("Lets learn something new",max_length=30)
logging.set_verbosity_error()
ans[0]["generated_text"][:100]

"Lets learn something new about the game's mechanics.\n\nPlayers will take on the role of an ancient al"

In [ ]:
classifier = pipeline("sentiment-analysis")
logging.set_verbosity_error()
ans = classifier("I've been waiting for a HuggingFace course my whole life.")
ans

[{'label': 'POSITIVE', 'score': 0.9598049521446228}]

In [ ]:
classifier = pipeline("zero-shot-classification")
ans = classifier(
    "This is a course not  about the Transformers library",
    candidate_labels=["education", "politics", "business"],
)
logging.set_verbosity_error()
ans

{'sequence': 'This is a course not  about the Transformers library',
 'labels': ['education', 'business', 'politics'],
 'scores': [0.5885071754455566, 0.32650691270828247, 0.08498593419790268]}

In [ ]:
unmask = pipeline("fill-mask")
ans=unmask("You are a <mask> Person",top_k=2)
logging.set_verbosity_error()
ans

[{'score': 0.10682491213083267,
  'token': 2822,
  'token_str': ' Real',
  'sequence': 'You are a Real Person'},
 {'score': 0.07431638240814209,
  'token': 26411,
  'token_str': ' Normal',
  'sequence': 'You are a Normal Person'}]

Named entity recognition (NER)


```
# PER(PERSON),ORG (ORGANIZATION),LOC (LOCATION) ,MISC (MISCELLANEOUS)
```



In [ ]:
ner = pipeline("ner",grouped_entities=True)
logging.set_verbosity_error()
ans=ner("I am vignay reddy from Jagityal studying at CVR COLLEGE OF ENGINEERING")
ans

/usr/local/lib/python3.11/dist-packages/transformers/pipelines/token_classification.py:181: UserWarning: `grouped_entities` is deprecated and will be removed in version v5.0.0, defaulted to `aggregation_strategy="AggregationStrategy.SIMPLE"` instead.
  warnings.warn(


[{'entity_group': 'LOC',
  'score': np.float32(0.9267577),
  'word': 'Jagityal',
  'start': 23,
  'end': 31},
 {'entity_group': 'ORG',
  'score': np.float32(0.48203757),
  'word': 'C',
  'start': 44,
  'end': 45},
 {'entity_group': 'MISC',
  'score': np.float32(0.7350932),
  'word': 'ENGINEERING',
  'start': 59,
  'end': 70}]

In [ ]:
qw = pipeline("question-answering")
ans= qw(
    question="Where do I work?",
    context="My name is Sylvain and I work at Hugging Face in Brooklyn",
)
logging.set_verbosity_error()
ans

{'score': 0.6949766278266907, 'start': 33, 'end': 45, 'answer': 'Hugging Face'}

In [ ]:
summarizer = pipeline("summarization")
ans=summarizer(
    """Nitish was bought by Sunrisers Hyderabad for Rs. 20 Lakh,
 in the 2023 Indian Premier League auction. He played just 2 matches in the league where he bowled a few overs but did not get to bat.[9] He had a breakout performance in the 2024 season,
  where he won the Emerging Player of the Year Award by scoring 303 runs with strike rate of 142 with crucial knocks against Punjab Kings and Rajasthan Royals and also picked
  up 3 wickets in the tournament showcasing
   his immense talent and consistency throughout the tournament. He was subsequently retained by SRH in the 2025 IPL Auction for Rs. 6 Crores.
   """)
ans[0]["summary_text"]

' Nitish was bought by Sunrisers Hyderabad for Rs. 20 Lakh in the 2023 Indian Premier League auction . He played just 2 matches in the league where he bowled a few overs but did not get to bat . He had a breakout performance in the 2024 season where he won the Emerging Player of the Year Award by scoring 303 runs with strike rate of 142 with crucial knocks against Punjab Kings and Rajasthan Royals .'

 BERT stands for Bidirectional Encoder Representations from Transformers.

In [ ]:
#Pretraining is the act of training a model from scratch: the weights are randomly initialized, and the training starts without any prior knowledge.

What happens inside the pipeline function?

In [ ]:
from transformers import AutoTokenizer

Creating ID'S

In [ ]:
checkpoint = "distilbert-base-uncased-finetuned-sst-2-english"
tokenizer = AutoTokenizer.from_pretrained(checkpoint)
raw_inputs = [
    "I've been waiting for a HuggingFace course my whole life.",
    "I hate this so much!",
]
inputs = tokenizer(raw_inputs, padding=True, truncation=True, return_tensors="pt")
inputs

/usr/local/lib/python3.11/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(


tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/629 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

{'input_ids': tensor([[  101,  1045,  1005,  2310,  2042,  3403,  2005,  1037, 17662, 12172,
          2607,  2026,  2878,  2166,  1012,   102],
        [  101,  1045,  5223,  2023,  2061,  2172,   999,   102,     0,     0,
             0,     0,     0,     0,     0,     0]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0]])}

In [ ]:
from transformers import AutoModel
checkpoint = "distilbert-base-uncased-finetuned-sst-2-english"
model = AutoModel.from_pretrained(checkpoint)
outputs = model(**inputs)
print(outputs.last_hidden_state.shape)

model.safetensors:   0%|          | 0.00/268M [00:00<?, ?B/s]

torch.Size([2, 16, 768])


Logists are producd by AutoModelForXXX module

In [ ]:
from transformers import AutoModelForSequenceClassification
checkpoint = "distilbert-base-uncased-finetuned-sst-2-english"
model = AutoModelForSequenceClassification.from_pretrained(checkpoint)
outputs = model(**inputs)
print(outputs.logits)

tensor([[-1.5607,  1.6123],
        [ 4.1692, -3.3464]], grad_fn=<AddmmBackward0>)


In [ ]:
import torch
predictions = torch.nn.functional.softmax(outputs.logits,dim=1)
print(predictions)
model.config.id2label

tensor([[4.0195e-02, 9.5980e-01],
        [9.9946e-01, 5.4418e-04]], grad_fn=<SoftmaxBackward0>)


{0: 'NEGATIVE', 1: 'POSITIVE'}

Instantiating Transformer Models

In [ ]:
from transformers import AutoConfig

bert_config = AutoConfig.from_pretrained("bert-base-cased")
print(type(bert_config))
gpt_config = AutoConfig.from_pretrained("gpt2")
print(type(gpt_config))



<class 'transformers.models.bert.configuration_bert.BertConfig'>


config.json:   0%|          | 0.00/665 [00:00<?, ?B/s]

<class 'transformers.models.gpt2.configuration_gpt2.GPT2Config'>


Tokenizer

In [ ]:
from transformers import AutoTokenizer
tokenizer = AutoTokenizer.from_pretrained("bert-base-cased")
sequence = "Using a Transformer network is simple"
tokens = tokenizer.tokenize(sequence)
print(tokens)
ids = tokenizer.convert_tokens_to_ids(tokens)
print(ids)
decoded_string = tokenizer.decode([7993, 170, 13809, 23763, 2443, 1110, 3014])
print(decoded_string)

['Using', 'a', 'Trans', '##former', 'network', 'is', 'simple']
[7993, 170, 13809, 23763, 2443, 1110, 3014]
Using a Transformer network is simple


In [ ]:
import torch
from transformers import AutoTokenizer, AutoModelForSequenceClassification
checkpoint = "distilbert-base-uncased-finetuned-sst-2-english"
tokenizer = AutoTokenizer.from_pretrained(checkpoint)
model = AutoModelForSequenceClassification.from_pretrained(checkpoint)
sequence = "I've been waiting for a HuggingFace course my whole life."
tokens = tokenizer.tokenize(sequence)
ids = tokenizer.convert_tokens_to_ids(tokens)
input_ids = torch.tensor([ids])
print("Input IDs:", input_ids)
output = model(input_ids)
print("Logits:", output.logits)
val =tokenizer.decode(input_ids[0])
print(val)

Input IDs: tensor([[ 1045,  1005,  2310,  2042,  3403,  2005,  1037, 17662, 12172,  2607,
          2026,  2878,  2166,  1012]])
Logits: tensor([[-2.7276,  2.8789]], grad_fn=<AddmmBackward0>)
i've been waiting for a huggingface course my whole life.


Two words/tokens are added. Lets see what it tells

In [ ]:
print(tokenizer.decode(model_inputs["input_ids"]))
print(tokenizer.decode(ids))

[CLS] i've been waiting for a huggingface course my whole life. [SEP]
i've been waiting for a huggingface course my whole life.


CLS => Classification token
SEP => Seperator to new line

In [ ]:
sequence = "I've been waiting for a HuggingFace course my whole life."
model_inputs = tokenizer(sequence)
print(model_inputs["input_ids"])
tokens = tokenizer.tokenize(sequence)
ids = tokenizer.convert_tokens_to_ids(tokens)
print(ids)

[101, 1045, 1005, 2310, 2042, 3403, 2005, 1037, 17662, 12172, 2607, 2026, 2878, 2166, 1012, 102]
[1045, 1005, 2310, 2042, 3403, 2005, 1037, 17662, 12172, 2607, 2026, 2878, 2166, 1012]


In [ ]:
import torch
from transformers import AutoTokenizer, AutoModelForSequenceClassification

checkpoint = "distilbert-base-uncased-finetuned-sst-2-english"
tokenizer = AutoTokenizer.from_pretrained(checkpoint)
model = AutoModelForSequenceClassification.from_pretrained(checkpoint)
sequences = ["I've been waiting for a HuggingFace course my whole life.", "So have I!"]

tokens = tokenizer(sequences, padding=True, truncation=True, return_tensors="pt")
output = model(**tokens)
output.logits

tensor([[-1.5607,  1.6123],
        [-3.6183,  3.9137]], grad_fn=<AddmmBackward0>)

##Hugging Face DataSets Overview

In [ ]:
from datasets import load_dataset
#Downloads the MRPC dataset from the GLUE benchmark
raw_datasets = load_dataset("glue", "mrpc")
raw_datasets

DatasetDict({
    train: Dataset({
        features: ['sentence1', 'sentence2', 'label', 'idx'],
        num_rows: 3668
    })
    validation: Dataset({
        features: ['sentence1', 'sentence2', 'label', 'idx'],
        num_rows: 408
    })
    test: Dataset({
        features: ['sentence1', 'sentence2', 'label', 'idx'],
        num_rows: 1725
    })
})